Update import workflow with better instructions

diff --git a/tools/import-workflow/workflow.yaml b/tools/import-workflow/workflow.yaml
--- a/tools/import-workflow/workflow.yaml
+++ b/tools/import-workflow/workflow.yaml
@@ -1,23 +1,50 @@
-name: "🔄 Import Workflow"
+name: 🔄 Import Smart Workflow
 
 on:
   workflow_dispatch:
     inputs:
-      workflow_description:
-        description: 'Name or description of the workflow'
+      workflow-id:
+        description: ID of the workflow to import
         required: true
 
 jobs:
-  import_workflow:
+  setup:
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout PR-Pilot-AI/smart-workflows
+        uses: actions/checkout@v2
+        with:
+          repository: PR-Pilot-AI/smart-workflows
+          token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Determine workflow file path
+        id: filepath
+        run: |
+          if [ -f tools/${{ github.event.inputs.workflow-id }}/workflow.yaml ]; then
+            echo "::set-output name=path::tools/${{ github.event.inputs.workflow-id }}/workflow.yaml"
+          elif [ -f automations/${{ github.event.inputs.workflow-id }}/workflow.yaml ]; then
+            echo "::set-output name=path::automations/${{ github.event.inputs.workflow-id }}/workflow.yaml"
+          else
+            echo "Path not found" && exit 1
+          fi
+      - name: Copy workflow file
+        id: print-workflow
+        run: |
+          workflow=$(cat ${{ steps.filepath.outputs.path }})
+          echo "WORKFLOW<<EOF"$'\n'"$workflow"$'\n'EOF >> "$GITHUB_OUTPUT"
+
       - name: Import Workflow
         uses: PR-Pilot-AI/smart-actions/quick-task@v1
         with:
           api-key: ${{ secrets.PR_PILOT_API_KEY }}
           agent-instructions: |
-            The user wants to import the following workflow: `${{ github.event.inputs.workflow_description }}`
-            Scrape `https://raw.githubusercontent.com/PR-Pilot-AI/smart-workflows/main/index.yaml` to see the available workflows.
-            If none match the user's input, abort.
-            Otherwise scrape the matching workflow file from `https://raw.githubusercontent.com/PR-Pilot-AI/smart-workflows/main/{'automations'|'tools'}/{workflow-slug}/workflow.yaml` 
-            and create it in `.github/workflows`.
+            Create a new file in `.github/workflows/` for the following workflow:
+
+            ---
+            
+            ${{ steps.print-workflow.outputs.WORKFLOW }}
+
+            ---
+            
+            The user can customize the workflow by instructing you using the `/pilot <prompt>` command. 
+            Read the `README.md` file to learn more about the project, then respond to the user with a few prompt 
+            suggestions on how they could customize the workflow for this project.
